# -*- coding: utf-8 -*-
"""Assignment-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zJGf9qP0RIjMc56CFt9rJVaVABFjulEm
"""

import numpy as np
def climate_solution(data_path,weights,n):
            all_data=np.concatenate([np.genfromtxt(data_path+f"{i+1}.csv",delimiter=',',skip_header=1) for i in range(n)])
            yield_of_corp=all_data@weights
            climate_results = np.concatenate((all_data, yield_of_corp.reshape(-1, 1)), axis=1)
            np.savetxt("climate_results.csv",climate_results,delimiter=',',fmt='%.2f',header='temperature,rainfall,humidity,yield_of_corp')  
            print("completed")   
data_path="https://raw.githubusercontent.com/svkarthik86/Advanced-python/main/climate_project/climate_data_station"
weights = np.array([0.3, 0.2, 0.5])
climate_solution(data_path,weights,10)